name: Publish to S3

on:
  push:
    branches:
      - master

jobs:
  build:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: asciidoctor

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: PublishToS3BucketSession
          role-skip-session-tagging: true

      - name: Copy files to S3 bucket with the AWS CLI
        run: |
          aws s3 sync ./build/docs s3://samjingwen.io --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
          
